#define TAM_INDIVIDUO 8
#define TAM_TOTAL 10 //TAM_INDIVIDUO + APTIDAO + FREQ. ACUMULADA
#define TAM_GERACAO 100
#define TAM_GERACAO_TOTAL 150 //TAM_GERACAO + FILHOS (DEVE SER PAR)
#define N_GERACOES 100

enum individuo
{
    S,E,N,D,M,O,R,Y,AVAL,FA,PORC
};
